spring.application.name=api-service
server.port=8080

# JWT
app.jwt.secret=${JWT_SECRET}
app.jwt.access-expiry=${JWT_ACCESS_EXPIRY:900}
app.jwt.refresh-expiry=${JWT_REFRESH_EXPIRY:604800}

# App
app.short-url-base=${SHORT_URL_BASE:http://localhost:8081}

# Logging
logging.level.io.lvoxx.ssurl=DEBUG
